config/routes.rb
Financials::Application.routes.draw do
  root 'transactions#index'
  resources :transactions, except: ['edit', 'update', 'new', 'create', 'destroy']
  resources :description_tags, except: ['edit', 'update', 'show']

  get 'upload/new' => 'upload#new', as: 'new_upload'
  post 'upload/account_data' => 'upload#account_data', as: 'upload_account_data'
  post 'upload/credit_card_data' => 'upload#credit_card_data', as: 'upload_credit_card_data'
  post 'upload/description_tags' => 'upload#description_tags', as: 'upload_description_tags'
  get 'reports' => 'reports#index', as: 'reports'
end

app/models/checking_transaction.rb
class CheckingTransaction < Transaction

  def self.translator
    {
      "Posting Date" => "transaction_date",
      "Amount" => "amount",
      "Description" => "description"
    }
  end

end

app/models/credit_card_transaction.rb
class CreditCardTransaction < Transaction

  def self.translator
    {
      "Trans Date" => "transaction_date",
      "Description" => "description",
      "Amount" => "amount"
    }
  end

end

app/models/description_tag.rb
class DescriptionTag < ActiveRecord::Base

  belongs_to :tag
  validates_uniqueness_of :description
  default_scope { order('description ASC') }

  def self.seek_by_description(q)
    search_by_description(q).first
  end

  def self.search_by_description(q)
    DescriptionTag.where("description LIKE ?", "%#{q}%")
  end

  def self.process_file(file_name)
    return if file_name.blank?
    csv_table = CSV.read(file_name, headers: true)
    csv_table.inject(0) {|sum, csv_row| sum += add_row_to_database(csv_row) }
  end

  def self.add_row_to_database(csv_row)
    tag = Tag.find_by_name(csv_row['tag_name'])
    DescriptionTag.create(description: csv_row['description'], tag_id: tag.id).valid? ? 1 : 0
  end

end

app/models/report.rb
module Report

  def income_summary
    income_transactions.inject(0){|sum, t| sum += t.amount.abs}
  end

  def expense_summary
    expense_transactions.inject(0){|sum, t| sum += t.amount.abs}
  end

  def income_transactions
    @income_transactions ||= transactions.select{ |trans| trans.tags.first.is_income? }
  end

  def expense_transactions
    @expense_transactions ||= transactions.select{ |trans| trans.tags.first.is_expense? }
  end

end

app/models/report/monthly_report.rb
module Report
  class MonthlyReport
    include Report

    def initialize(month)
      @month = month
    end

    def month_name
      Date::MONTHNAMES[@month]
    end

    def transactions
      @transactions ||= Transaction.where('extract(month from transaction_date) = ?', @month)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :transaction_tags
  has_many :transactions, through: :transaction_tags

  has_many :description_tags
  validates_uniqueness_of :name

  def is_income?
    self.income_expense == "income"
  end

  def is_expense?
    self.income_expense == "expense"
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  has_many :transaction_tags
  has_many :tags, through: :transaction_tags

  validates_uniqueness_of :identifier
  default_scope { order('transaction_date ASC') }

  after_save :auto_set_tag

  def self.process_file(file_name)
    return if file_name.blank?
    csv_table = CSV.read(file_name, headers: true)
    csv_table.inject(0) {|sum, csv_row| sum += add_row_to_database(csv_row) }
  end

  def self.add_row_to_database(csv_row)
    Transaction.create(filtered_params(csv_row)).valid? ? 1 : 0
  end

  def self.filtered_params(csv_row)
    new_params = translated_values(csv_row)
    {
      transaction_date: DateUtils.parse_date(new_params['transaction_date']),
      amount: clean_amount(new_params['amount']),
      description: new_params['description'],
      identifier: create_identifier(new_params)
    }
  end

  def self.translated_values(csv_row)
    {}.tap do |h|
      csv_row.each {|k, v| h[db_key(k)] = v}
    end
  end

  def self.db_key(key)
    translator.fetch(key, '')
  end

  def self.create_identifier(params)
    Digest::SHA1.hexdigest params.to_s
  end

  def self.clean_amount(amt)
    amt ? amt.gsub('$', '') : '0.0'
  end

  def transaction_date_display
    transaction_date.strftime("%-m/%-d/%Y")
  end

  def auto_set_tag
    dtag = DescriptionTag.seek_by_description(self.description)
    TransactionTag.create(transaction_id: self.id, tag_id: dtag.tag_id) if dtag.present?
  end

  def tags_display
    self.tags.map{ |tag| tag.name }.join(', ')
  end

end

app/models/transaction_tag.rb
class TransactionTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :transaction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/description_tags_controller.rb
class DescriptionTagsController < ApplicationController
  def index
    @description_tags = DescriptionTag.includes(:tag)
  end

  def new
    @description_tag = DescriptionTag.new
  end

  def create
    redirect_to description_tags_path
  end

  def destroy
    redirect_to description_tags_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @month = params[:month] || DateTime.now.month
    @monthly_report = Report::MonthlyReport.new(@month)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.includes(:tags)
  end

  def show
    @transaction = Transaction.find(params[:id])
  end
end

app/controllers/upload_controller.rb
require 'csv'

class UploadController < ApplicationController
  before_filter :set_title

  def new; end

  def account_data
    count = CheckingTransaction.process_file(params[:filename].path)
    flash[:message] = "#{count} records have been added"
    redirect_to new_upload_path
  end

  def credit_card_data
    count = CreditCardTransaction.process_file(params[:filename].path)
    flash[:message] = "#{count} records have been added"
    redirect_to new_upload_path
  end

  def description_tags
    count = DescriptionTag.process_file(params[:filename].path)
    flash[:message] = "#{count} records have been added"
    redirect_to new_upload_path
  end

  private
  def set_title
    @title = "Upload a File"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/description_tags_helper.rb
module DescriptionTagsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/description_tags/index.html.haml
%h1 Description Tags
.panel.panel-default
  .panel-heading
    %table.table
      %tr
        %th Description
        %th Tag
      - @description_tags.each do |trans|
        %tr
          %td=trans.description
          %td=trans.tag.name

app/views/description_tags/new.html.haml
%h1 DescriptionTags#new
%p Find me in app/views/description_tags/new.html.haml

app/views/layouts/_navigation.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{href: root_path} Financials
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{href: transactions_path} Transactions
        %li
          %a{href: description_tags_path} Descriptions
        %li
          %a{href: reports_path} Reports
        %li
          %a{href: new_upload_path} Upload

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= @title ? @title : "Financials"
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/navigation'
    .container.main
      = yield
    %footer

app/views/pages/index.html.haml
%h1 Page#index
%p Find me in app/views/page/index.html.haml

app/views/reports/index.html.haml
%h1
  Reports
%ul.nav.nav-pills
  %li.dropdown
    %a#drop4{role: "button", href: '#', data:{toggle: "dropdown"}}
      Dropdown
      %b.caret
    %ul#menu1.dropdown-menu{role: 'menu', "aria-labelledby" => "dropdownMenu1"}
      %li
        Test2

.month-summary
  %h3
    = @monthly_report.month_name
  %h4
    Expenses: (#{number_to_currency(@monthly_report.expense_summary)})
  %h4
    Income: #{number_to_currency(@monthly_report.income_summary)}

app/views/transactions/index.html.haml
%h1 Transactions
.panel.panel-default
  .panel-heading
    Account Transactions
    %table.table
      %tr
        %th Date
        %th Description
        %th Amount
        %th Tags
      - @transactions.each do |trans|
        %tr
          %td=trans.transaction_date_display
          %td=trans.description
          %td=number_to_currency(trans.amount)
          %td=trans.tags_display

app/views/upload/new.html.haml
- if flash[:message].present?
  %h3 #{flash[:message]}

.row
  .col-md-6
    %h4 Upload Checking Data
    = form_tag upload_account_data_path, multipart: true do
      = label_tag "File Name:"
      = file_field_tag :filename
      %br
      = submit_tag "Submit"
  .col-md-6
    %h4 Upload Credit Card Data
    = form_tag upload_credit_card_data_path, multipart: true do
      = label_tag "File Name:"
      = file_field_tag :filename
      %br
      = submit_tag "Submit"
.row
  .col-md-6
    %h4 Upload Description Tag
    = form_tag upload_description_tags_path, multipart: true do
      = label_tag "File Name:"
      = file_field_tag :filename
      %br
      = submit_tag "Submit"